### ISSUE TITLE
invalid literal for int() with base 10

### ISSUE THREAD

**Issue by rlewkowicz** [lozuwa/impy#13]
```
Traceback (most recent call last):
  File "cropset.py", line 19, in <module>
    main()
  File "cropset.py", line 16, in main
    obda.reduceDatasetByRois(offset = offset, outputImageDirectory = images_output_path, outputAnnotationDirectory = annotations_output_path)
  File "/home/ryan/anaconda3/envs/impy/lib/python3.6/site-packages/impy/ObjectDetectionDataset.py", line 391, in reduceDatasetByRois
    outputAnnotationDirectory = outputAnnotationDirectory)
  File "/home/ryan/anaconda3/envs/impy/lib/python3.6/site-packages/impy/ObjectDetectionDataset.py", line 447, in reduceImageDataPointByRoi
    annotation = ImageAnnotation(path = annotationPath)
  File "/home/ryan/anaconda3/envs/impy/lib/python3.6/site-packages/impy/ImageAnnotation.py", line 25, in __init__
    self.boundingBoxes = self.getBoundingBoxes(self.objects)
  File "/home/ryan/anaconda3/envs/impy/lib/python3.6/site-packages/impy/ImageAnnotation.py", line 68, in getBoundingBoxes
    xmin = int(coordinates.find("xmin").text)
ValueError: invalid literal for int() with base 10: '897.0416467209191'
```

The XML in part:

```
...
    <bndbox>
        <xmin>897.0416467209191</xmin>
        <ymin>501.42446808510635</ymin>
        <xmax>1010.0909526089038</xmax>
        <ymax>545.5436170212765</ymax>
    </bndbox>
</object><object>
    <name>test</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
        <xmin>848.32934418382</xmin>
        <ymin>499.586170212766</ymin>
        <xmax>954.0258496888464</xmax>
        <ymax>551.0585106382979</ymax>
    </bndbox>

...

```

**Comment by rlewkowicz** [comment]
I "fixed" it for me. I replaced all instances of int with float. Util.py and ObjectDetectionDataset.py with some index issues were the only 2 I had to change back. Hyper hacky, I'm just too tired right now to do it right.
