### ISSUE TITLE
getBoundingBoxes should be float instead of int

### ISSUE THREAD

**Issue by sainisanjay** [lozuwa/impy#16]
Hi @lozuwa I think in "ImageAnnotation.py" and getBoundingBoxes function bounding box coordinates should be float instead of int. 
```
def getBoundingBoxes(self, objects = None):
		boundingBoxes = []
		for i in range(len(objects)):
			# Find bndbox
			coordinates = objects[i].find("bndbox")
			# Get coordinates
			xmin = float(coordinates.find("xmin").text)
                        xmax = float(coordinates.find("xmax").text)
                        ymin = float(coordinates.find("ymin").text)
                        ymax = float(coordinates.find("ymax").text)
			boundingBoxes.append([xmin, ymin, xmax, ymax])
		return boundingBoxes

```

**Comment by sainisanjay** [comment]
Hi @lozuwa, 
after changing bounding box coordinates into float(as per above comment), i am getting below error. Kindly help me to resolve.
```
python3 reducing_big_images.py 
  0%|                                                                                                      | 0/62899 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "reducing_big_images.py", line 38, in <module>
    main()
  File "reducing_big_images.py", line 35, in main
    obda.reduceDatasetByRois(offset = offset, outputImageDirectory = images_output_path, outputAnnotationDirectory = annotations_output_path)
  File "/home/adas/.local/lib/python3.6/site-packages/impy/ObjectDetectionDataset.py", line 391, in reduceDatasetByRois
    outputAnnotationDirectory = outputAnnotationDirectory)
  File "/home/adas/.local/lib/python3.6/site-packages/impy/ObjectDetectionDataset.py", line 522, in reduceImageDataPointByRoi
    Util.save_img(frame = frame[RoiYMin:RoiYMax, RoiXMin:RoiXMax, :],
TypeError: slice indices must be integers or None or have an __index__ method
```
Original Image size `1820x940` and i am reducing into `910x470`.  I believe offset is not a problem.
